try
{
let a=1,b
let c=a+b;
console.log(c)
}
catch(err){
console.log(err);
}
